%-------------------------------------------------------------
% plik wyœwietlaj¹cy odpowiednie opcje w menu MATERIA£
%-------------------------------------------------------------
% Hubert Gawryœ   2013-01-07
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% nr_dof     - liczba wprowadzonych wêz³ów
% All_coord  - tablica wspó³rzêdnych wêz³owów
% All_dof    - tablica stopni swobody wêz³ów
%-------------------------------------------------------------
if (get(material1,'Value')==1)
    uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(3,:),'HorizontalAlignment','center',...
        'String',[' '],'Position',[80 wysokoscrzedu222-7 300 22]);
    material2=uicontrol(gcf,'style','popupmenu','FontSize',8,'FontWeight','bold',...
        'BackGroundColor','w','HorizontalAlignment','center',...
        'String','ALUM|B15|B20|B25|B30|B37|B45|B50|B55|B60|C14|C16|C18|C20|C22|C24|C27|C30|C35|C40|C45|C50|D18|D24|D30|D35|D40|D50|D60|D70|GL24c|GL24h|GL28c|GL28h|GL32c|GL32h|GL36c|GL36h|S 185|S 235|S 275|S 275QS|S 355|S 355QS|S 420|S 460|STAL|STAL 18G2|STAL 18G2AV|STAL R|STAL R35|STAL R45|STAL St3S|STAL St4|STAL StOS', ...
        'Position',[80 wysokoscrzedu222 100 15]);
elseif (get(material1,'Value')==2)
    uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(3,:),'HorizontalAlignment','center',...
        'String',[' '],'Position',[80 wysokoscrzedu222-7 300 22]);
    uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
        'String',['E '],'Position',[80 wysokoscrzedu222 30 15]);
    E1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor','w','HorizontalAlignment','center',...
        'String','','Position',[120 wysokoscrzedu222 120 15]);
    uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
        'String',['v = '],'Position',[250 wysokoscrzedu222 30 15]);
    v1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor','w','HorizontalAlignment','center',...
        'String','','Position',[290 wysokoscrzedu222 30 15]);
end
%-------------------------------------------------------------
hp=uipanel('Title','Nowy Materia³','FontSize',8,'BackgroundColor',...
    kol2(3,:),'ForeGroundColor','w','Position',[ 0.05 0.7 0.45 0.24]);
%-------------------------------------------------------------