%-------------------------------------------------------------
% plik menu ELEMENTY
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% nr_element - liczba wprowadzonych elementów
% All_edofs  - tablica wêz³ów elementów
% Ex, Ey, Ez - odpowiednie wspó³rzêdne pocz¹tku i koñca elementu
% Edof       - macierz topologii elementów
%-------------------------------------------------------------
clear_fig(1,lmenu);
if nr_element>0
    subplot(1,2,2);
    l_rysunek2;
end
wysokoscrzedu11=490;
wysokoscrzedu22=350;
Pos2=get(fig,'Position');
hp=uipanel('Title','Nowy Element','FontSize',8, ...
    'BackgroundColor',kol2(3,:),'ForeGroundColor','w' ...
    ,'Position',[ 0.05 0.7 0.45 0.2]);
%-------------------------------------------------------------
if nr_element>0
    for k=1:nr_element
        
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['W' num2str(All_edofs(k,1)) ',1 = '], ...
            'Position',[100 wysokoscrzedu22-k*20 30 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['W' num2str(All_edofs(k,1)) ',2 = '], ...
            'Position',[180 wysokoscrzedu22-k*20 30 15]);
        %-----------------------------------------------------
        ee(k)=uicontrol(gcf,'style','checkbox','Position', ...
            [260 wysokoscrzedu22-k*20 30 15],...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center');
        %-----------------------------------------------------
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_edofs(k,2)), ...
            'Position',[140 wysokoscrzedu22-k*20 30 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_edofs(k,3)), ...
            'Position',[220 wysokoscrzedu22-k*20 30 15]);
    end
end
%-------------------------------------------------------------
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['W1= '],'Position',[100 wysokoscrzedu11 30 15]);
e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
    'String','','Position',[140 wysokoscrzedu11 30 15]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['W2= '],'Position',[180 wysokoscrzedu11 30 15]);
e2=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
    'String','','Position',[220 wysokoscrzedu11 30 15]);
%-------------------------------------------------------------
d1 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:), ...
    'ForeGroundColor','w', ...
    'FontWeight','bold', ...
    'FontSize',8,...
    'String','Dodaj Element', ...
    'Position',[220 440 130 25],...
    'Callback','nr_element=nr_element+1; nr_alert=1; All_alert; wczytaj_elementy;l_wektorwspolrzednych; l_elementy');
%-------------------------------------------------------------
if nr_element>0
    d2 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:), ...
        'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
        'String','Usuñ Element','Position',[220 350 130 25],...
        'Callback', 'update_element;l_wektorwspolrzednych; l_elementy;');
end
%-------------------------------------------------------------
if nr_element>0
    hp=uipanel('Title','Elementy Dodane','FontSize',8, ...
        'BackgroundColor',kol2(3,:),'ForeGroundColor','w', ...
        'Position',[ 0.05 0.47-nr_element*20/wymiary 0.45 0.2+nr_element*20/wymiary]);
end
%-------------------------------------------------------------