%-------------------------------------------------------------
% plik menu MATERIA£
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% nr_material- liczba elementów z przypisanym materia³em
% All_EvG    - tablica zawieraj¹ca dane materia³owe elementów
%-------------------------------------------------------------
clear_fig(1,lmenu);
wysokoscrzedu111=350;
wysokoscrzedu222=490;
%-------------------------------------------------------------
Pos2=get(fig,'Position');
%-------------------------------------------------------------
if nr_material>0
    for k=1:nr_material
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['E' num2str(All_EvG(k,4)) ' = '],...
            'Position',[80 wysokoscrzedu111-k*20 30 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['G' num2str(All_EvG(k,4)) ' = '],...
            'Position',[250 wysokoscrzedu111-k*20 30 15]);
        mm(k)=uicontrol(gcf,'style','checkbox', ...
            'Position',[420 wysokoscrzedu111-k*20 15 15],...
            'BackGroundColor','y','HorizontalAlignment','center');
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_EvG(k,1)), ...
            'Position',[120 wysokoscrzedu111-k*20 120 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_EvG(k,3)),...
            'Position',[290 wysokoscrzedu111-k*20 120 15]);
    end
end
%-------------------------------------------------------------
d1 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),...
    'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
    'String','Dodaj Materia³','Position',[80 440 130 25],...
    'Callback', 'nr_material=nr_material+1; nr_alert=2; All_alert; wczytaj_material; l_material');
if nr_material>0
    d2 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),...
        'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
        'String','Usuñ materia³','Position',[220 350 130 25],...
        'Callback', 'update_material; l_material');
end
d2 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),...
    'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
    'String','Zastosuj do wszystkich','Position',[220 440 130 25],...
    'Callback', 'nr_material=nr_element; nr_alert=3; All_alert; wczytaj_material2; l_material');
if nr_material>0
    hp=uipanel('Title','Dodane Materia³y','FontSize',8,'BackgroundColor',...
        kol2(3,:),'ForeGroundColor','w','Position',...
        [ 0.05 0.47-nr_material*20/wymiary 0.55 0.2+nr_material*20/wymiary]);
end
%-------------------------------------------------------------
material1=uicontrol(gcf,'style','popupmenu','FontSize',8,'FontWeight','bold',...
    'BackGroundColor','w','HorizontalAlignment','center',...
    'String','Materia³ standardowy|Materia³ w³asny', ...
    'Position',[80 wysokoscrzedu222+35 150 15],'Callback','draw_material1');
draw_material1;
%-------------------------------------------------------------