%-------------------------------------------------------------
% plik menu PRZEKRÓJ
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% nr_cross   - liczba elementów z wprowadzonym przekrojem
% All_iiak   - tablica zawieraj¹ca przekrój danego elementu
% All_eo     - tablica zawieraj¹ca usytuowanie przekroju w
%              przestrzeni
%-------------------------------------------------------------
clear_fig(1,lmenu);
h_v41=350;
h_v42=510;
h_v43=540;
w_c41=30;
w_c42=55;
w_c43=150;
w_ods4=10;
w_s=70;
Pos2=get(fig,'Position');
%-------------------------------------------------------------
if nr_cross>0
    for k=1:nr_cross
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['Iz' num2str(All_iiak(k,5)) ' = '],'Position',[w_s h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['Iy' num2str(All_iiak(k,5)) ' = '],'Position',[w_s+2*w_ods4+w_c41+w_c42 h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['A' num2str(All_iiak(k,5)) ' = '],'Position',[w_s+2*(2*w_ods4+w_c41+w_c42) h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['Kv' num2str(All_iiak(k,5)) ' = '],'Position',[w_s+3*(2*w_ods4+w_c41+w_c42) h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['eX' num2str(All_eo(k,4)) ' = '],'Position',[w_s+4*(2*w_ods4+w_c41+w_c42) h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['eY' num2str(All_eo(k,4)) ' = '],'Position',[w_s+4*(2*w_ods4+w_c41+w_c42)+2*w_ods4+2*w_c41 h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['eZ' num2str(All_eo(k,4)) ' = '],'Position',[w_s+4*(2*w_ods4+w_c41+w_c42)+4*w_ods4+4*w_c41 h_v41-k*20 w_c41 15]);
        %-------------------------------------------------------------
        pp(k)=uicontrol(gcf,'style','checkbox','Position',[w_s+4*(2*w_ods4+w_c41+w_c42)+4*w_ods4+4*w_c41+2*w_c41+2*w_ods4 h_v41-k*20 15 15],...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center');
        %-------------------------------------------------------------
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_iiak(k,1)),'Position',[w_s+w_c41+w_ods4 h_v41-k*20 w_c42 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_iiak(k,2)),'Position',[w_s+w_c41+w_ods4+2*w_ods4+w_c41+w_c42 h_v41-k*20 w_c42 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_iiak(k,3)),'Position',[w_s+w_c41+w_ods4+2*(2*w_ods4+w_c41+w_c42) h_v41-k*20 w_c42 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_iiak(k,4)),'Position',[w_s+w_c41+w_ods4+3*(2*w_ods4+w_c41+w_c42) h_v41-k*20 w_c42 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_eo(k,1)),'Position',[w_s+4*(2*w_ods4+w_c41+w_c42)+w_c41+w_ods4 h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_eo(k,2)),'Position',[w_s+4*(2*w_ods4+w_c41+w_c42)+3*(w_c41+w_ods4) h_v41-k*20 w_c41 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_eo(k,3)),'Position',[w_s+4*(2*w_ods4+w_c41+w_c42)+5*(w_c41+w_ods4) h_v41-k*20 w_c41 15]);
    end
end

d1 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
    'String','Dodaj przekrój','Position',[80 450 130 25],...
    'Callback', 'nr_cross=nr_cross+1; nr_alert=4; All_alert; wczytaj_przekroj; l_przekroj');
if nr_cross>0
    d2 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
        'String','Usuñ przekrój','Position',[220 350 130 25],...
        'Callback', 'update_cross; l_przekroj');
end
d2 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
    'String','Zastosuj do wszystkich','Position',[220 450 130 25],...
    'Callback', 'nr_cross=nr_element; nr_alert=5; All_alert; wczytaj_przekroj2; l_przekroj');
%-------------------------------------------------------------
if nr_cross>0
    hp=uipanel('Title','Dodane materia³y','FontSize',8,'BackgroundColor',kol2(3,:),'ForeGroundColor','w','Position',[ 0.05 0.47-nr_cross*20/wymiary 0.90 0.2+nr_cross*20/wymiary]);
end
%-------------------------------------------------------------
profil2=uicontrol(gcf,'style','popupmenu','FontSize',8,'FontWeight','bold',...
    'BackGroundColor','w','HorizontalAlignment','center',...
    'String','Tablica dwuteowników|Przekrój prostok¹tny|Przekrój w³asny', ...
    'Position',[w_s h_v43 w_c43 15],'Callback','draw_cross1');
draw_cross1;
%-------------------------------------------------------------
