%-------------------------------------------------------------
% plik menu PRZEMIESZCZENIA(g)
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% ed  - plik zawieraj¹cy przemieszczenia elementu
%-------------------------------------------------------------
clear_fig(1,lmenu);
%-------------------------------------------------------------
h_v1=520;
h_v2=350;
w_c1=60;
w_c2=50;
w_ods=10;
w_s=70;
Pos2=get(fig,'Position');
%-------------------------------------------------------------
hp=uipanel('Title','Przemieszczenia wêz³ów elementów','FontSize',8,...
    'BackgroundColor',kol2(3,:),'ForeGroundColor','w','Units','Pixels',...
    'Position',[ w_c1-50 500-nr_element*20 780 80+nr_element*20]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['ed= '],'Position',[30 h_v1+20 30 15]);
for k=1:nr_element
    e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
        'String',k,'Position',[w_c1-40 h_v1-k*20 30 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,1)),'Position',[w_c1 h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,2)),'Position',[w_c1+w_ods+w_c2 h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,3)),'Position',[w_c1+2*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,4)),'Position',[w_c1+3*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,5)),'Position',[w_c1+4*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,6)),'Position',[w_c1+5*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,7)),'Position',[w_c1+6*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,8)),'Position',[w_c1+7*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,9)),'Position',[w_c1+8*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,10)),'Position',[w_c1+9*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,11)),'Position',[w_c1+10*(w_ods+w_c2) h_v1-k*20 50 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(ed(k,12)),'Position',[w_c1+11*(w_ods+w_c2) h_v1-k*20 50 15]);
end
%-------------------------------------------------------------