%-------------------------------------------------------------
% plik menu REAKCJE
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% All_dof    - tablica stopni swobody wêz³ów
% R          - wektor reakcji podporowych
%-------------------------------------------------------------
clear_fig(1,lmenu);
h_v1=520;
h_v2=350;
w_c1=90;
w_c2=100;
w_ods=10;
w_s=70;
Pos2=get(fig,'Position');
%-------------------------------------------------------------
hp=uipanel('Title','Reakcje podporowe','FontSize',8,...
    'BackgroundColor',kol2(3,:),'ForeGroundColor','w','Units','Pixels',...
    'Position',[ w_c1-60 440-nr_bc*20 720 130+nr_bc*20]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Reakcje wêz³owe'],'Position',[w_c1 h_v1+10 w_c2*2 15]);
k2=0;
for k=1:6:(nr_dof*6)
    k2=k2+1;
    e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
        'String',All_dof(k2,7),...
        'Position',[w_c1-40 h_v1-k2*20 30 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(R(k)),...
        'Position',[w_c1 h_v1-k2*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(R(k+1)),...
        'Position',[w_c1+w_ods+w_c2 h_v1-k2*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(R(k+2)),...
        'Position',[w_c1+2*(w_ods+w_c2) h_v1-k2*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(R(k+3)),...
        'Position',[w_c1+3*(w_ods+w_c2) h_v1-k2*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(R(k+4)),...
        'Position',[w_c1+4*(w_ods+w_c2) h_v1-k2*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(R(k+5)),...
        'Position',[w_c1+5*(w_ods+w_c2) h_v1-k2*20 w_c2 15]);
end
%-------------------------------------------------------------