%-------------------------------------------------------------
% plik menu OBCI¥¯ENIA SKUPIONE
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% nr_sforce  - liczba wprowadzonych si³ wêz³owych
% All_sforce - tablica zawieraj¹ca dane o si³ach wêz³owych
%-------------------------------------------------------------
clear_fig(1,lmenu);
wysokoscrzedu111111=330;
wysokoscrzedu222222=490;
Pos2=get(fig,'Position');
%-------------------------------------------------------------
if nr_sforce>0
    for k=1:nr_sforce
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['Wêze³(' num2str(All_sforce(k,7)) ') = '],...
            'Position',[80 wysokoscrzedu111111-k*20 120 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_sforce(k,1:6)),...
            'Position',[250 wysokoscrzedu111111-k*20 120 15]);
        oo(k)=uicontrol(gcf,'style','checkbox',...
            'Position',[420 wysokoscrzedu111111-k*20 15 15],...
            'BackGroundColor','y','HorizontalAlignment','center');
    end
    uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
        'String',['N Vy Vz T My Mz'],...
        'Position',[250 wysokoscrzedu111111 120 15]);
end
%-------------------------------------------------------------
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Rodzaj '],'Position',[80 wysokoscrzedu222222 50 15]);
force_type1=uicontrol(gcf,'style','popupmenu','FontSize',8,'FontWeight','bold',...
    'BackGroundColor','w','HorizontalAlignment','center',...
    'String','N|Vy|Vz|T|My|Mz','Callback','rys_jednostka',...
    'Position',[140 wysokoscrzedu222222 40 15]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Wartoœæ'],'Position',[190 wysokoscrzedu222222 50 15]);
s_force1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
    'String','','Position',[250 wysokoscrzedu222222 50 15]);
rys_jednostka;
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Wêze³'],'Position',[340 wysokoscrzedu222222 45 15]);
s_force2=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
    'String','','Position',[395 wysokoscrzedu222222 30 15]);
%-------------------------------------------------------------
d1 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),...
    'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
    'String','Dodaj obci¹¿enie','Position',[80 440 130 25],...
    'Callback', 'nr_sforce=nr_sforce+1; nr_alert=14; All_alert; load_sforce; l_skupione');
if nr_sforce>0
    d2 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),...
        'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
        'String','Usuñ obci¹¿enie','Position',[245 350 130 25],...
        'Callback', 'update_sforce; l_skupione');
end
%-------------------------------------------------------------
hp=uipanel('Title','Nowe obci¹¿enie','FontSize',8,...
    'BackgroundColor',kol2(3,:),'ForeGroundColor','w',...
    'Position',[ 0.05 0.7 0.5 0.2]);
if nr_sforce>0
    hp=uipanel('Title','Dodane obci¹¿enia','FontSize',8,...
        'BackgroundColor',kol2(3,:),'ForeGroundColor','w',...
        'Position',[ 0.05 0.47-nr_sforce*20/wymiary 0.55 0.2+nr_sforce*20/wymiary]);
end
%-------------------------------------------------------------