%-------------------------------------------------------------
% plik menu WÊZ£Y
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% nr_dof     - liczba wprowadzonych wêz³ów
% All_coord  - tablica wspó³rzêdnych wêz³owów
%-------------------------------------------------------------
clear_fig(1,lmenu);
if nr_dof>0
    subplot(5,5,[9,10,14,15,19,20]);
    l_rysunek1;
end
wysokoscrzedu1=490;
wysokoscrzedu2=350;
Pos2=get(fig,'Position');
%-------------------------------------------------------------
if nr_dof>0
    for k=1:nr_dof
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['X(P' num2str(All_coord(k,4)) ') = '],...
            'Position',[100 wysokoscrzedu2-k*20 30 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['Y(P' num2str(All_coord(k,4)) ') = '],...
            'Position',[180 wysokoscrzedu2-k*20 30 15]);
        uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
            'String',['Z(P' num2str(All_coord(k,4)) ') = '],...
            'Position',[260 wysokoscrzedu2-k*20 30 15]);
        cc(k)=uicontrol(gcf,'style','checkbox',...
            'Position',[340 wysokoscrzedu2-k*20 15 15],...
            'BackGroundColor',kol2(5,:),'HorizontalAlignment','center');
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_coord(k,1)),...
            'Position',[140 wysokoscrzedu2-k*20 30 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_coord(k,2)),...
            'Position',[220 wysokoscrzedu2-k*20 30 15]);
        uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
            'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
            'String',num2str(All_coord(k,3)),...
            'Position',[300 wysokoscrzedu2-k*20 30 15]);
    end
end
%-------------------------------------------------------------
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['X = '],'Position',[100 wysokoscrzedu1 30 15]);
w1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
    'String','','Position',[140 wysokoscrzedu1 30 15]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Y = '],'Position',[180 wysokoscrzedu1 30 15]);
w2=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
    'String','','Position',[220 wysokoscrzedu1 30 15]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Z = '],'Position',[260 wysokoscrzedu1 30 15]);
w3=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
    'String','','Position',[300 wysokoscrzedu1 30 15]);
%-------------------------------------------------------------
d1 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),...
    'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
    'String','Dodaj Wêze³','Position',[220 440 130 25],...
    'Callback', 'nr_dof=nr_dof+1; wczytaj_wezly;l_wektorwspolrzednych; l_wezly');
if nr_dof>0
    d2 = uicontrol(gcf,'style','pushbutton','BackGroundColor',kol2(2,:),...
        'ForeGroundColor','w','FontWeight','bold','FontSize',8,...
        'String','Usuñ wêze³','Position',[220 350 130 25],...
        'Callback', 'update_dof;l_wektorwspolrzednych; l_wezly');
end
%-------------------------------------------------------------
hp=uipanel('Title','Nowy Wêze³','FontSize',8,...
    'BackgroundColor',kol2(3,:),'ForeGroundColor','w',...
    'Position',[ 0.05 0.7 0.45 0.2]);
if nr_dof>0
    hp=uipanel('Title','Wêz³y Dodane','FontSize',8,...
        'BackgroundColor',kol2(3,:),'ForeGroundColor','w',...
        'Position',[ 0.05 0.47-nr_dof*20/wymiary 0.45 0.2+nr_dof*20/wymiary]);
end
%-------------------------------------------------------------