%-------------------------------------------------------------
% plik menu WYKRES SI£ PRZEKROJOWYCH
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
clear_fig(1,lmenu);
sila=uicontrol(gcf,'style','popupmenu','FontSize',8,'FontWeight','bold',...
    'BackGroundColor','w','HorizontalAlignment','center',...
    'String','N|Vy|Vz|T|My|Mz','Position',[140 550 40 15],...
    'Callback','czysc_sub; wykres_sil');
napisy_s=uicontrol(gcf,'style','checkbox',...
    'Position',[165 520 15 15],...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'Callback','czysc_sub; wykres_sil');
grid_v=uicontrol(gcf,'style','checkbox',...
    'Position',[165 500 15 15],...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'Callback','czysc_sub; wykres_sil');
hp=uipanel('Title','WYKRES','FontSize',8,...
    'BackgroundColor',kol2(3,:),'ForeGroundColor','w',...
    'Position',[ 0.04 0.78 0.2 0.2]);
%-------------------------------------------------------------
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['TYP si³y'],'Position',[50 550 80 15]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Wartoœci si³'],'Position',[50 520 100 15]);
uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String',['Siatka'],'Position',[50 500 100 15]);
%-------------------------------------------------------------
