function t=opcje_menu(nr1,nr2)
%-------------------------------------------------------------
% plik zawieraj¹cy nazwy pozycji menu
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
t='';
switch 1
    case 1
        switch nr1
            case 1
                M={'GEOMETRIA';...
                    'WÊZ£Y';...
                    'ELEMENTY'};
            case 2
                M={'TYP';...
                    'MATERIA£';...
                    'PRZEKRÓJ'};
            case 3
                M={'WIÊZY';...
                    'PODPORY';...
                    'PRZEGUBY'};
            case 4
                M={'OBCI¥¯ENIA';...
                    'SKUPIONE';...
                    'ROZ£O¯ONE'};
            case 5
                M={'OBLICZENIA';...
                    'WYKONAJ OBLICZENIA'};...
            case 6
                M={'WYNIKI';...
                    'PRZEMIESZCZENIA(g)';...
                    'PRZEMIESZCZENIA(el)';...
                    'REAKCJE PODPOROWE';...
                    'SI£Y PRZEKROJOWE(el)';...
                    'WYKRES PRZEMIESZCZEÑ';...
                    'WYKRES SI£ PRZEKROJOWYCH';...
                    'EMPTY';...
                    'ZAPIS DO PLIKU';...
                    'ODCZYT Z PLIKU'};
        end
end
t=cell2mat(M(nr2,:));
%-------------------------------------------------------------
