%-------------------------------------------------------------
% plik rysuj¹cy wyniki si³ przekrojowych dla wybranego prêta
%-------------------------------------------------------------
% Hubert Gawryœ   2012-10-25
% Instytut Technologii Informatycznych w In¿ynierii L¹dowej(L-5)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
h_v1=500;
h_v2=350;
w_c1=330;
w_c2=60;
w_ods=10;
w_s=70;
[N_beam,M_beam]=size(eci);
Scr=get(fig,'Position');
%-------------------------------------------------------------
hp=uipanel('Title','Si³y przekrojowe prêta','FontSize',8,...
    'BackgroundColor',kol2(3,:),'ForeGroundColor','w','Units','Pixels',...
    'Position',[ 270 460-N_beam*20 500 100+N_beam*20]);
for k=1:N_beam
    e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
        'String',num2str(eci(k,(get(es_popup,'Value')))),'Position',[w_c1-40 h_v1-k*20 30 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(es(k,1,(get(es_popup,'Value')))),'Position',[w_c1 h_v1-k*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(es(k,2,(get(es_popup,'Value')))),'Position',[w_c1+w_ods+w_c2 h_v1-k*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(es(k,3,(get(es_popup,'Value')))),'Position',[w_c1+2*(w_ods+w_c2) h_v1-k*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(es(k,4,(get(es_popup,'Value')))),'Position',[w_c1+3*(w_ods+w_c2) h_v1-k*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(es(k,5,(get(es_popup,'Value')))),'Position',[w_c1+4*(w_ods+w_c2) h_v1-k*20 w_c2 15]);
    e1=uicontrol(gcf,'style','edit','FontSize',8,'FontWeight','bold',...
        'BackGroundColor',kol2(6,:),'HorizontalAlignment','center',...
        'String',num2str(es(k,6,(get(es_popup,'Value')))),'Position',[w_c1+5*(w_ods+w_c2) h_v1-k*20 w_c2 15]);
end
e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String','x=','Position',[w_c1-40 h_v1+w_ods 30 15]);
e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String','N','Position',[w_c1 h_v1+w_ods w_c2 15]);
e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String','Vy','Position',[w_c1+w_ods+w_c2 h_v1+w_ods w_c2 15]);
e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String','Vz','Position',[w_c1+2*(w_ods+w_c2) h_v1+w_ods w_c2 15]);
e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String','T','Position',[w_c1+3*(w_ods+w_c2) h_v1+w_ods w_c2 15]);
e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String','My','Position',[w_c1+4*(w_ods+w_c2) h_v1+w_ods w_c2 15]);
e1=uicontrol(gcf,'style','text','FontSize',8,'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),'HorizontalAlignment','center',...
    'String','Mz','Position',[w_c1+5*(w_ods+w_c2) h_v1+w_ods w_c2 15]);
%-------------------------------------------------------------